### ISSUE TITLE
Arcade Joystick problem

### ISSUE THREAD

**Issue by salamander2** [salamander2/Robot2014#1]
In arcade mode, the left and right of the joystick are reversed.

**Comment by sirsavary** [comment]
I believe that this is intentional design. Only way around it is to write your own drivetrain code.

**Comment by salamander2** [comment]
THanks

**Comment by sirsavary** [comment]
9/10

**Comment by salamander2** [comment]
Switching the motors did nothing except reverse the front and back. **Which could be very useful!**
`drivetrain(victor1,victor2)`  vs `drivetrain(victor2,victor1)`

**Comment by salamander2** [comment]
Here is another thing we can try:

```
 drivetrain.setInvertedMotor(RobotDrive.MotorType.kFrontLeft,true);
 drivetrain.setInvertedMotor(RobotDrive.MotorType.kRearLeft,true);
 drivetrain.setInvertedMotor(RobotDrive.MotorType.kFrontRight,true);
 drivetrain.setInvertedMotor(RobotDrive.MotorType.kRearRight,true);
```

We would have to do this for both of our driveTrains.
**This works!!**
Also, note that there are built in functions to handle "limit()" and "squaredInputs()" We don't have to write our own.
